name: domoticz
version: 3.4834-1
summary: DomoticZ
description: Very light weight home automation system
confinement: devmode

# Domoticz is a Home Automation System that lets you monitor and
# configure various devices like: Lights, Switches, various
# sensors/meters like Temperature, Rain, Wind, UV, Electra, Gas, Water
# and much more. Notifications/Alerts can be sent to any mobile device.

apps:
    domoticz:
        command: opt/domoticz/domoticz
            -www 80
            -dbase $SNAP_DATA/domoticz.db
            -log $SNAP_DATA/domoticz.log
            -loglevel 1
            -syslog
        daemon: simple
        plugs: [network, network-bind]

parts:
#    # http://developer.telldus.com/wiki/TellStickInstallationSource
#    telldus-core:
#        plugin: cmake
#        source: http://download.telldus.se/TellStick/Software/telldus-core/telldus-core-2.1.2.tar.gz
##        source: http://git.telldus.com/telldus.git
##        source-subdir: telldus-core
##        source-tag: "v2.1.2"
##        source-type: git
#        configflags:
#            -   -DCMAKE_INSTALL_PREFIX=/usr
##            -   -DFORCE_COMPILE_FROM_TRUNK=TRUE
#        build-packages:
#            -   libftdi-dev
#            -   libconfuse-dev
    openzwave:
        plugin: make
        source: git://github.com/OpenZWave/open-zwave.git
        source-tag: "v1.4"
        make-parameters:
            -   PREFIX=/usr
        build-packages:
            -   libudev-dev
            -   pkg-config
        organize:
            usr/local/lib: usr/lib
    domoticz:
        plugin: cmake
        source: git://github.com/domoticz/domoticz.git
        source-tag: "3.4834"
        after: [ openzwave ]
        configflags:
            -   -DCMAKE_BUILD_TYPE=Release
            -   -DCMAKE_INSTALL_PREFIX=/opt/domoticz # workaround
            -   -DUSE_STATIC_OPENZWAVE=OFF
        build-packages:
            -   libboost-thread-dev
            -   libcurl4-openssl-dev
            -   libssl-dev
            -   libusb-dev
            -   zlib1g-dev
        stage-packages:
            -   libcurl4-openssl-dev
        snap:
            -   -opt/domoticz/History.txt
            -   -opt/domoticz/License.txt
            -   -opt/domoticz/updatedomo
